import type { Product } from './product.js';

export const PRODUCTS: Product[] = [
  {
    id: 'product-001',
    name: 'Teclado Mecânico',
    description: 'Teclado mecânico compacto com iluminação ajustável.',
    price: 399.9,
    image: 'https://placehold.co/600x400/png?text=Teclado+Mecanico',
    category: 'Periféricos',
    stock: 10,
  },
  {
    id: 'product-002',
    name: 'Mouse Sem Fio',
    description: 'Mouse ergonômico com conexão sem fio e bateria recarregável.',
    price: 189.9,
    image: 'https://placehold.co/600x400/png?text=Mouse+Sem+Fio',
    category: 'Periféricos',
    stock: 18,
  },
  {
    id: 'product-003',
    name: 'Monitor 27 Polegadas',
    description: 'Monitor IPS com resolução QHD e taxa de atualização de 144 Hz.',
    price: 1799.9,
    image: 'https://placehold.co/600x400/png?text=Monitor+27',
    category: 'Monitores',
    stock: 7,
  },
  {
    id: 'product-004',
    name: 'Headset USB',
    description: 'Headset com microfone removível e controle de volume integrado.',
    price: 279.9,
    image: 'https://placehold.co/600x400/png?text=Headset+USB',
    category: 'Áudio',
    stock: 14,
  },
  {
    id: 'product-005',
    name: 'Webcam Full HD',
    description: 'Webcam 1080p com foco automático e microfone integrado.',
    price: 329.9,
    image: 'https://placehold.co/600x400/png?text=Webcam+Full+HD',
    category: 'Acessórios',
    stock: 9,
  },
  {
    id: 'product-006',
    name: 'Hub USB-C',
    description: 'Hub compacto com HDMI, USB 3.0 e leitor de cartões.',
    price: 249.9,
    image: 'https://placehold.co/600x400/png?text=Hub+USB-C',
    category: 'Acessórios',
    stock: 21,
  },
  {
    id: 'product-007',
    name: 'SSD Externo 1 TB',
    description: 'Armazenamento portátil com conexão USB-C e capacidade de 1 TB.',
    price: 649.9,
    image: 'https://placehold.co/600x400/png?text=SSD+Externo',
    category: 'Armazenamento',
    stock: 11,
  },
  {
    id: 'product-008',
    name: 'Suporte para Notebook',
    description: 'Suporte ajustável em alumínio para notebooks de até 16 polegadas.',
    price: 159.9,
    image: 'https://placehold.co/600x400/png?text=Suporte+Notebook',
    category: 'Acessórios',
    stock: 25,
  },
];
